### PR TITLE
docker-compose improvements

### PR DESCRIPTION
**Pull request by dshatz**
Makes the project configurable using .env files and runnable both individually and through the graphsense-setup project.
See commit messages and README for more information.
If you notice anything that is unclear or can be improved don't hesitate to mention that.

### CODE REVIEW

**Comment by defconst** [comment]
Why do you need in `"com.codahale.metrics" % "metrics-core" % "3.0.2"` in build.sbt?

**Comment by dshatz** [comment]
> Why do you need in `"com.codahale.metrics" % "metrics-core" % "3.0.2"` in build.sbt?

I was experiencing a problem when building the jar. There was an error like `NoClassDefFound: com.codahale.metrics...` which I failed to resolve in any other way. If you remove that new dependency, do you get the same?

**Comment by defconst** [comment]
> I was experiencing a problem when building the jar. There was an error like `NoClassDefFound: com.codahale.metrics...` which I failed to resolve in any other way. If you remove that new dependency, do you get the same?

@dshatz ok, maybe required in Spark 3, we currently only have Spark 2.4.5 on our cluster. Will test this later, after graphsense-blocksci setup is finished.

**Comment by defconst** [comment]
https://github.com/graphsense/graphsense-setup/commit/1b31567a1a00478f5f6abcb0e594126da91395c7

**Pull request closed without merging**
